### ISSUE TITLE
Installation with pip --user

### ISSUE THREAD

**Issue by GuillaumeSeren** [guyzmo/git-repo#1]
Hey,
I would like to install 'git-repo' but I prefer to install in my userspace with pip install --user,
here is the error I get
```python
pip install --user git-repo                                                                                                                                                                       1 
Collecting git-repo
  Downloading git-repo-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-build-4e20i_j2/git-repo/.eggs/setuptools_markdown-0.2-py3.4.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.1.3
    Downloading https://pypi.python.org/packages/source/p/pypandoc/pypandoc-1.1.3.zip#md5=771f376bf9c936a90159cd94235998c2
    Processing pypandoc-1.1.3.zip
    Writing /tmp/easy_install-tobd_snv/pypandoc-1.1.3/setup.cfg
    Running pypandoc-1.1.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tobd_snv/pypandoc-1.1.3/egg-dist-tmp-g5fpg11a
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__pycache__.__init__.cpython-34: module references __file__
    Patching wheel building...
    creating /tmp/pip-build-4e20i_j2/git-repo/.eggs/pypandoc-1.1.3-py3.4.egg
    Extracting pypandoc-1.1.3-py3.4.egg to /tmp/pip-build-4e20i_j2/git-repo/.eggs
    
    Installed /tmp/pip-build-4e20i_j2/git-repo/.eggs/pypandoc-1.1.3-py3.4.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-4e20i_j2/git-repo/setup.py", line 38, in <module>
        zip_safe=False
      File "/usr/lib64/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib64/python3.4/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/lib64/python3.4/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-4e20i_j2/git-repo/.eggs/setuptools_markdown-0.2-py3.4.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-build-4e20i_j2/git-repo/.eggs/pypandoc-1.1.3-py3.4.egg/pypandoc/__init__.py", line 50, in convert
        outputfile=outputfile, filters=filters)
      File "/tmp/pip-build-4e20i_j2/git-repo/.eggs/pypandoc-1.1.3-py3.4.egg/pypandoc/__init__.py", line 68, in _convert
        raise RuntimeError('Missing format!')
    RuntimeError: Missing format!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4e20i_j2/git-repo
```

I think it should work ( I do the same for other user-managed packages ), so maybe there is a problem in the pypy recipe ?

**Comment by guyzmo** [comment]
this is due to the fact that README.md is missing from the archive, and thus cannot be converted at install time. Though I thought I had that fixed with that release. I'm anyway preparing a new release for the soonest, I'm just currently testing and testing the latest code to make it solid.

Meanwhile, you can use sources on git to check it out.

**Comment by GuillaumeSeren** [comment]
Hey,
I have successfully installed it from git yesterday → '2fc27f1',
also in userspace with ' python3 setup.py install --user'.

It went well, and I will try to configure it today, so I can give you some feedback.

Tell me when you upgrade the pip recipe I will test again :suspect:

**Comment by guyzmo** [comment]
just upgraded the pip recipe to `1.5.0` (yup, I added a patch number in case I have to re-upload many times to pip ☺). It's matching the repository's head.

**Comment by guyzmo** [comment]
I tested locally with and without --user and it's installing fine from pip. 

Please reopen if you have this issue again!

**Comment by GuillaumeSeren** [comment]
I confirm pip install is working well, and '--upgrade' as well !

Thanks for the feedback :+1:
