### ISSUE TITLE
Can't authenticate using when using github 2FA

### ISSUE THREAD

**Issue by guiniol** [guyzmo/git-repo#113]
git-repo does ask for the 2FA code, but then returns with a `Fatal error: 401 Must specify two-factor authentication OTP code.`

Here is the log running `git-repo -v config`

```
Fatal error: 401 Must specify two-factor authentication OTP code.
------------------------------------
Traceback (most recent call last):
  File "…/git_repo/repo.py", line 550, in main
    return GitRepoRunner(args).run()
  File "…/git_repo/kwargparse.py", line 68, in run
    return self._action_dict[frozenset(args)](self)
  File "…/git_repo/repo.py", line 542, in do_config
    setup_service(service)
  File "…/git_repo/repo.py", line 514, in setup_service
    token = service.get_auth_token(username, password, prompt=loop_input)
  File "…/git_repo/services/ext/github.py", line 319, in get_auth_token
    raise err
  File "…/git_repo/services/ext/github.py", line 313, in get_auth_token
    note_url='https://github.com/guyzmo/git-repo')
  File "…/github3/github.py", line 121, in authorize
    json = self._json(self._post(url, data=data), 201)
  File "…/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "…/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 401 Must specify two-factor authentication OTP code.
```

* [git-repo-v.txt](https://github.com/guyzmo/git-repo/files/737158/git-repo-v.txt)

And here is the log running `git-repo -vvv config`

```
Fatal error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…/git_repo/repo.py", line 550, in main
    return GitRepoRunner(args).run()
  File "…/git_repo/kwargparse.py", line 68, in run
    return self._action_dict[frozenset(args)](self)
  File "…/git_repo/repo.py", line 542, in do_config
    setup_service(service)
  File "…/git_repo/repo.py", line 514, in setup_service
    token = service.get_auth_token(username, password, prompt=loop_input)
  File "…/git_repo/services/ext/github.py", line 313, in get_auth_token
    note_url='https://github.com/guyzmo/git-repo')
  File "…/github3/github.py", line 121, in authorize
    json = self._json(self._post(url, data=data), 201)
  File "…/github3/models.py", line 145, in _post
    return self._session.post(url, data, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "…/github3/session.py", line 85, in request
    new_response = self.handle_two_factor_auth(args, kwargs)
  File "…/github3/session.py", line 68, in handle_two_factor_auth
    return super(GitHubSession, self).request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

* [git-repo-vvv.txt](https://github.com/guyzmo/git-repo/files/737160/git-repo-vvv.txt)

**Comment by guyzmo** [comment]
ok I looked for references: sigmavirus24/github3.py#667

**Comment by guyzmo** [comment]
hum… I cannot replicate the issue. I just tried after enabling it in github, and authenticated with a code generated on my iphone. I really can't tell what went wrong with your setup. :-s

**Comment by guyzmo** [comment]
I'm marking as `wontfix` up until I can replicate…

**Comment by guiniol** [comment]
So. I had the same issue as the guy in sigmavirus24/github3.py#667 
I wonder if something's up with github 2FA.
