### ISSUE TITLE
Unable to install on MacOSX

### ISSUE THREAD

**Issue by sandeep048** [guyzmo/git-repo#31]
```
sudo pip install git+https://github.com/guyzmo/git-repo.git
The directory '/Users/Sandeep/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Sandeep/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+https://github.com/guyzmo/git-repo.git
  Cloning https://github.com/guyzmo/git-repo.git to /tmp/pip-Cah3BZ-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-Cah3BZ-build/setup.py", line 67
        class Version(Command, metaclass=VersionInfo):
                                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-Cah3BZ-build/
```

**Comment by ZyanKLee** [comment]
this error does occur on ubuntu 16.04 as well.

**Comment by guyzmo** [comment]
Hello, what version of pip and python are you using? 

This is tool has been coded be used only with python3 (and tested with python3.4 and 3.5). I totally dropped support for py2, as I'm using many py3 only features.

Though there's a guard to make it explicit upon install within the setup, that's deceived by the `metaclass=` syntax in the setup file. So I'll fix it and release a new version, so you get a nice looking error message ☺

So to install use:

    pip3 install git-repo
