### ISSUE TITLE
Fork from yourself throws incorrect error

### ISSUE THREAD

**Issue by pyhedgehog** [guyzmo/git-repo#84]
```console
# git hub -v fork pyhedgehog/pygogs
Fatal error: name 'ResourceError' is not defined
------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/git_repo/repo.py", line 544, in main
    return GitRepoRunner(args).run()
  File "/usr/lib/python3.4/site-packages/git_repo/kwargparse.py", line 68, in run
    return self._action_dict[frozenset(args)](self)
  File "/usr/lib/python3.4/site-packages/git_repo/repo.py", line 329, in do_fork
    service.run_fork(self.user_name, self.repo_name, branch=self.branch)
  File "/usr/lib/python3.4/site-packages/git_repo/services/service.py", line 300, in run_fork
    raise ResourceError("Cannot fork a project from yourself.")
NameError: name 'ResourceError' is not defined
```

**Comment by guyzmo** [comment]
👌 and thank you!

I've replicated this, and I'll fix that ASAP!
