### ISSUE TITLE
Clone from empty repository throws incorrect error

### ISSUE THREAD

**Issue by pyhedgehog** [guyzmo/git-repo#85]
```console
# git hub -v clone pyhedgehog/choco-packages
Cloning choco-packages…
Fatal error: name 'ResourceNotFoundError' is not defined
------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/git_repo/repo.py", line 348, in do_clone
    service.clone(self.user_name, self.repo_name, self.branch)
  File "/usr/lib/python3.4/site-packages/git_repo/services/service.py", line 237, in clone
    self.pull(remote, branch)
  File "/usr/lib/python3.4/site-packages/git_repo/services/service.py", line 208, in pull
    remote.pull(branch, progress=pb)
  File "/usr/lib/python3.4/site-packages/git/remote.py", line 771, in pull
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/lib/python3.4/site-packages/git/remote.py", line 638, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/lib/python3.4/site-packages/git/cmd.py", line 291, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull --progress -v github master
  stderr: 'fatal: Couldn't find remote ref master'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/git_repo/repo.py", line 544, in main
    return GitRepoRunner(args).run()
  File "/usr/lib/python3.4/site-packages/git_repo/kwargparse.py", line 68, in run
    return self._action_dict[frozenset(args)](self)
  File "/usr/lib/python3.4/site-packages/git_repo/repo.py", line 357, in do_clone
    raise ResourceNotFoundError(err.args[2].decode('utf-8')) from err
NameError: name 'ResourceNotFoundError' is not defined
```

**Comment by guyzmo** [comment]
👌 same kind of errors!
basically, it's only the exceptions that I forgot to import in the repo module.
